### ISSUE TITLE
Json does not show as printed when program exists

### ISSUE THREAD

**Issue by Nickiel12** [ratatui/ratatui-website#13]
This is more of a "is it a feature or a bug" issue, but because it is new users who are using this tutorial, I believe this should be fixed. What happens, is the `app.print_json()` is called before the terminal change window is called, so the new user does not see the json actually be printed.

I will be working on a fix that moves the `app.print_json()` to the end of the main function, but the surrounding tutorial also needs to be updated to explain this change.

**Comment by joshka** [comment]
Sounds good - this is definitely worth a small section in the tutorial talking about exiting the alternative screen (with a link to more info) - here's a PR with a bunch more info on raw mode in its docs:
- https://github.com/ratatui-org/ratatui/pull/280
- https://github.com/ratatui-org/ratatui/pull/280/files#diff-b1bbc13b52b920f2cfb842559dcccfa6a836168e2061e22d8a897c82af70c3a7
