### ISSUE TITLE
Async counter app: EventHandler diff is wrong

### ISSUE THREAD

**Issue by j0ni** [ratatui/ratatui-website#130]
The examples on [this page](https://ratatui.rs/tutorial/counter-async-app/async-event-stream.html) has several differences which don't appear in the diff, as well as mistakes in the bits which are shown to differ.

It's like one of those "how many differences can you find" puzzles I remember from my extremely bored childhood 🤣

**Comment by kdheepak** [comment]
Oh no 😅 this is my bad. Thanks for opening an issue, I know it must be frustrating having to figure this out.

**Comment by kdheepak** [comment]
I ended up removing the verbose old vs new code and just kept the comparison diff. The code shown in the diff is primarily for illustration purposes, and I'm not expecting users to implement the intermediate of converting to tokio channels. The final code below using `tokio::select!` macro is what people should be using. 

I'm going to rework this entire section of the tutorial as part of #124 so I'll address more comments in there. Open to more feedback if you have any.

**Comment by j0ni** [comment]
Not frustrating! Mostly just lulzworthy, exacerbated by being tired enough to think it was just my lack of acuity 😭 But thank you for dealing with it so quickly, and thanks again for donating labor ❤️
