### ISSUE TITLE
Improvement of the ratatui tutorial for the Counter-App

### ISSUE THREAD

**Issue by javaLux** [ratatui/ratatui-website#146]
Hello first of all a big thank you to you for this great ratatui tutorial.
I have discovered a small error in the counter app tutorial. The test case ``test_app_decrement_counter`` for the structure app is faulty.

**Current test case**
``app.rs``
```
#[cfg(test)]
mod tests {
  use super::*;
  #[test]
  fn test_app_increment_counter() {
    let mut app = App::default();
    app.increment_counter();
    assert_eq!(app.counter, 1);
  }

  #[test]
  fn test_app_decrement_counter() {
    let mut app = App::default();
    app.decrement_counter();
    assert_eq!(app.counter, 0);
  }
}
```

**Solution**
```
#[cfg(test)]
mod test {
    use super::*;

    #[test]
    fn test_app_increment_counter() {
        let mut app = App::new();
        app.increment();
        assert_eq!(app.counter, 1);
    }

    #[test]
    fn test_app_decrement_counter() {
        let mut app = App::new();
        app.decrement();
        assert_eq!(app.counter, -1);
    }
}
```

**Comment by kdheepak** [comment]
Good catch! Would you like to submit a pull request to fix this? If not, I can do it later tonight!

**Comment by kdheepak** [comment]
`decrement_counter` uses `self.counter.checked_sub(1)` and `self.counter` is of type `u8`, so the test is in fact correct. 

<img width="680" alt="image" src="https://github.com/ratatui-org/ratatui-book/assets/1813121/c65e26eb-7523-4637-b4c8-64e50cbb0ec7">

It the `counter` was `i8` instead, then the test would be `-1`.
