### ISSUE TITLE
Alternative preview instead of gh-pages hack

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui-website#149]
Currently we use this github action:

https://github.com/ratatui-org/ratatui-book/blob/acd261ec00c6da60f8d99a8b591c4065f2923b49/.github/workflows/mdbook.yml#L75-L99

Which has a few downsides:

1. `git log --oneline --all --graph` is not useful unless you remove all the commits from `gh-pages` 

<img width="282" alt="image" src="https://github.com/ratatui-org/ratatui-book/assets/1813121/2020dd82-5a18-45b7-8611-04e97ed971c4">

2. It only works for branches in this repo and does not show previews for PRs from external contributors 

The solution is to use netlify or some other alternative preview method.

**Comment by joshka** [comment]
See https://github.com/joshka/ratatui-book/tree/netlify for the netlify version of this with zola

https://github.com/ratatui-org/ratatui-book/compare/main...joshka:ratatui-book:netlify

**Comment by joshka** [comment]
Using cloudflare instead
