### ISSUE TITLE
Mention rendering `Clear` widget before popup window in "Center a Rect" section

### ISSUE THREAD

**Issue by fritzrehde** [ratatui/ratatui-website#157]
I just found a bug in one of my ratatui TUIs where I didn't clear the screen with
```rust
        frame.render_widget(Clear, area);
```
before rendering to a popup window. If I remember correctly, I used https://ratatui.rs/how-to/layout/center-a-rect.html as inspiration to create that popup window. I think it might make sense to mention there (or maybe elsewhere if you know a better place) that clearing such a centered rect is required for most use-cases (i.e. if you are drawing underneath that popup window as well).
Thanks!

**Comment by kdheepak** [comment]
Thanks for making the issue!
