### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by kyu08** [ratatui/ratatui-website#161]
Thank you for maintaining ratatui and its great documents! 😃

I found some broken links in this https://ratatui.rs/tutorial/json-editor/ui.html.

<img width="1468" alt="image" src="https://github.com/ratatui-org/ratatui-book/assets/49891479/08877a19-1911-49a7-b84a-443baf9bae97">

These 2 links are broken.
Applicable codes are [here](https://github.com/ratatui-org/ratatui-book/blob/e30efa4988ff3a28eb00e431a448420fcef7d771/src/tutorial/json-editor/ui.md?plain=1#L33-L34).

I thought this codes are itented to link somewhere in https://ratatui.rs/concepts/layout/index.html, but I don't know the relevant part.😓

**Comment by kdheepak** [comment]
Thanks for reporting!

**Comment by kyu08** [comment]
Thank you for very quick fix too! :)

**Comment by kdheepak** [comment]
I'm surprised that linkcheck didn't catch this for us.

https://github.com/ratatui-org/ratatui-book/blob/ebf79f8d88bf3ee2a3d1a32fc0a462fe579000e6/book.toml#L26

This is something I have to look into.
