### ISSUE TITLE
Expect message in tutorials > counter app > multiple files > event.rs is wrong

### ISSUE THREAD

**Issue by NotThatRqd** [ratatui/ratatui-website#165]
```rust
if event::poll(timeout).expect("no events available") {
```

Should be something like:

```rust
if event::poll(timeout).unwrap() {
```

If there are no events `event::poll` will return `Ok(false)`, the documentation doesn't specify why it could fail but it is some sort of IO error.
https://docs.rs/crossterm/latest/crossterm/event/fn.poll.html

**Comment by joshka** [comment]
It should very likely instead return a Result (or an Option) and use ? to avoid panicking. Would you be interested in submitting a PR to fix this up?

**Comment by NotThatRqd** [comment]
It's inside a thread, I don't know how it would return. Everywhere else `expect` is used, I just don't know why poll would return an error, it's not specified, so `unwrap` is probably fine?

**Comment by NotThatRqd** [comment]
I made a pull request: #167

**Comment by kdheepak** [comment]
Thanks for making a PR!
