### ISSUE TITLE
Update json editor code to ratatui 0.24

### ISSUE THREAD

**Issue by Sejsel** [ratatui/ratatui-website#170]
Currently, the json editor code is still built against ratatui 0.22. Notably, that means that the[ ui function signature](https://github.com/ratatui-org/ratatui-book/blob/0dfe64049cdf7b2327de109de2fa05225e241fe7/code/ratatui-json-editor-app/src/ui.rs#L14) is now wrong as Frame is no longer generic.

**Comment by joshka** [comment]
Thanks for letting us know. Would you be interested in writing a PR to fix this?

**Comment by Sejsel** [comment]
I am not sure I will have time to do it soon, so if anyone else wants to do this, feel free to.

**Comment by joshka** [comment]
No problem.
