### ISSUE TITLE
Move top level `features` page to `develop-apps` in content and sidebar

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui-website#190]
Skimming through the sidebar, I think the `Features` page feels like it is the odd one out. Alternatively, rename it to feature flags.

**Comment by joshka** [comment]
agreed - I think it ended up there because we had a reference section in the old site

**Comment by joshka** [comment]
I moved it under the installation section instead and renamed it to feature flags in https://github.com/ratatui-org/website/pull/193
