### ISSUE TITLE
Make astro `npm run dev` ignore watching `target` folder

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui-website#191]
when running `cargo run` in any `code` folder, `npm run dev` crashes sometimes for odd reasons. `vite` must have a configuration to ignore folders when watching for changes.

**Comment by aycanocal** [comment]
Hi, I want to work on this. Can you assign it to me?

**Comment by joshka** [comment]
Go for it - thanks!
If you run into any problems feel free to reach on the Ratatui discord / matrix channels.

**Comment by joshka** [comment]
Hey @aycanocal I found that adding the following in our astro.config.mjs helps avoid a reload when you rebuild rust projects. Not sure if this is the best approach - does this seem right?:
```
  vite: {
    server: {
      watch: {
        ignored: ["**/target/**/*"],
      },
    },
  }
```

**Comment by aycanocal** [comment]
Hey @joshka, I was going to submit the same changes. However, I'm having an issue in build, thus i couldn't commit.

```
Found 4 invalid links in 4 files.

▶ installation//
  └─ /concepts/backends/

▶ introduction/
  └─ /concepts/backends/

▶ installation/feature-flags/
  └─ /concepts/backends/

▶ tutorials/json-editor/app/
  └─ /concepts/rendering/

 error   Links validation failed.
```
 
 Do you know how i can resolve this issue?

**Comment by joshka** [comment]
Can you tell me:
a) what you're running that gives you an error?
b) what is the state of your repo (i.e. what commit id are you working from)?

My guess at the most likely thing to have happened is that you're using a slightly older commit and we changed a bunch of things in the astro.config.mjs file and so you've found something that conflicts with your changes.

If you're not on the most recent, commit your work (use `--no-verify` to avoid running the pre-commit checks if needed) and rebase onto the current main (`git switch main; git pull; git sw your-branch` unless your branch is main)
Alternatively if you're more comfortable, you can stash your changes (`git stash push -m 'wip: ignoring target in watch'`) pull main and pop your stash (`git stash pop`)

If you need more real time help on this, I'd encourage you to see who's online on discord and ask in the #help channel.

**Comment by aycanocal** [comment]
Thanks for the info, i was behind the main branch.
