### ISSUE TITLE
Add links in header

### ISSUE THREAD

**Issue by joshka** [ratatui/ratatui-website#194]
I'd like to see the following links in the header next to the github and discord icons:
- https://docs.rs/ratatui/latest/ratatui/
- https://crates.io/crates/ratatui/

It would be nice to add text labels to the existing github and discord icons too (though test how this looks on mobile - this is low priority)

https://starlight.astro.build/reference/overrides/#header is the component to override.

**Comment by orhun** [comment]
FWIW I submitted an issue to Starlight for adding the Matrix logo: https://github.com/withastro/starlight/discussions/1155
