### ISSUE TITLE
Add description of serde flag to docs

### ISSUE THREAD

**Issue by Apromixately** [ratatui/ratatui-website#241]
https://ratatui.rs/installation/feature-flags/#serde could use a description of what that flag means.

**Comment by joshka** [comment]
This is documented in the main docs.rs page:

? serde — enables serialization and deserialization of style and color types using the [Serde crate]. This is useful if you want to save themes to a file.

Moving this to the website though which doesn't contain this info.

**Comment by joshka** [comment]
Would you be able to cut a PR to fix this?
