### ISSUE TITLE
Add page to developer docs that uses all features supported by SSG

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui-website#257]
This will allow us to check in one location for all the features used in Astro + extensions when there are updates

**Comment by Valentin271** [comment]
Just to clarify this one, you want to make a list of all the astro extensions we are using right?

**Comment by kdheepak** [comment]
Not just a list but example usage as well. When we update a dependency or extension, I want to be able to go to one page to see how all the extensions behave and if it looks good there it probably will look good everywhere else on the website.

**Comment by Valentin271** [comment]
Oh I see, sort of a debug page.

Do you think this should be somewhat hidden? `_<url>`, maybe don't link to it?

**Comment by kdheepak** [comment]
No need to hide it because I want to find it quickly as well :)

I think it is fine for such page to be in a developer docs section. It's also useful for users to see how to make an admonish note, or a mermaid diagram if they want to contribute to the docs.

**Comment by kdheepak** [comment]
I've added a section on this page about how to use various features supported by our website: https://ratatui.rs/developer-guide/website/
