### ISSUE TITLE
Add page to developer docs for commonly used `git` commands for submitting PRs for contributors

### ISSUE THREAD

**Issue by kdheepak** [ratatui/ratatui-website#259]
Information regarding rebase, squashing, signing, etc.

**Comment by orhun** [comment]
marking as good first issue

**Comment by Valentin271** [comment]
A rough list of what to mention + interrogations:

- `git rebase`
  - rebase on main
  - squash commits
- `git commit`
  - `--amend`
  - `--no-verify` (this is useful for the website when the commit hook doesn't work)
- `git push`
  - `--no-verify`
  - `-f`
  - `-u` (to avoid people waiting on cargo make and then git telling there is no remote tracking)
- Signing commits

References to guides/articles might be nice if you know of some.

---

- `git branch`? (this might be a bit too much, we won't explain how to `add` and `commit` basic stuff)
- `git log` summary? (We sometime tell people the history needs to be searched to find the rational for a decision)
- Include usage/reference to commitizen/lazygit/other common tools?
- The whole fork - pull request process?

**Comment by vjurcutiu** [comment]
Hey, can I work on this?

**Comment by Valentin271** [comment]
Sure go ahead! Don't hesitate to ask if you need any help.

**Comment by vjurcutiu** [comment]
Thanks @Valentin271, I will start working on it and keep you updated.

**Comment by Valentin271** [comment]
Closed by #437
