### ISSUE TITLE
FAQ: How do I align text in a Table?

### ISSUE THREAD

**Issue by pythops** [ratatui/ratatui-website#342]
Original title: "Choose different position for the text in columns in the table widget."

## Problem
I want to be able to choose the position of the text in the columns of a table.
Right now, it seems that the text is always position at the left.

**Comment by joshka** [comment]
Cell accepts Text. Each line in the text has an alignment, which is respected when rendering the cell.

```rust
Cell::new(Line::from("asdf").alignment(Alignment::Right))
```

**Comment by pythops** [comment]
Excellent, I did not see that one. 
Thanks for the answer.

**Comment by joshka** [comment]
Re-opening this to suggest this as a good question to be added to the FAQs.
https://ratatui.rs/faq/

**Comment by Valentin271** [comment]
[How to > Display text](https://ratatui.rs/how-to/render/display-text/) could also use a mention to alignment.
