### ISSUE TITLE
Where is ratatui-counter app / example?

### ISSUE THREAD

**Issue by rubiesonthesky** [ratatui/ratatui-website#453]
Where is ratatui-counter template app? Has it been renamed or removed?

* https://ratatui.rs/templates/component/#counter--text-input-demo points that it should be in `component/ratatui-counter` in https://github.com/ratatui-org/templates repository, but I can't find it
* https://ratatui.rs/tutorials/counter-async-app/ has link "async ratatui counter app" that points to https://github.com/ratatui-org/templates/tree/main/component/ratatui-counter but that gives 404

I hope that I'm filing this issue in right repository :)

**Comment by kdheepak** [comment]
Thanks for opening the issue! I removed it as part of this PR: https://github.com/ratatui-org/templates/pull/45 in preparation for the new tutorial.

If you are interested in reading the code, you can check it out here: https://github.com/ratatui-org/async-template

I'll leave this issue open till the new tutorial is merged.
