### ISSUE TITLE
Lack of continuity while doing examples

### ISSUE THREAD

**Issue by illiteratewriter** [ratatui/ratatui-website#490]
The [Async Event Stream page](https://ratatui.rs/tutorials/counter-async-app/async-event-stream/) of the Async Counter App points to the multiple file counter example ([page](https://ratatui.rs/tutorials/counter-app/multiple-files/event/)). But since the multiple files part of the Counter example is no longer a part of the tutorial (the link is working but one has to take extra effort to go back and do the lesson, and since it is not in the tree, the next and previous pages are also missing) there is incoherence.

>Previously, in the multiple file version of the counter app, in [event.rs](https://ratatui.rs/tutorials/counter-app/multiple-files/event/) we created an EventHandler using std::thread::spawn, i.e. OS threads.

Personally I feel that, that lesson should exist at least just so those who are new to rust can learn on `mpsc`

**Comment by kdheepak** [comment]
Thanks for reporting! Good find.

The async tutorials are being rewritten from scratch in https://github.com/ratatui-org/website/pull/440. For now, I'm just going to remove the orphan link so it is not confusing.

**Comment by joshka** [comment]
I YOLO'ed the push (figuring that there wasn't anything in the change that broke things). Turns out that the push didn't deploy correctly either. Investigating and will fix.
