### ISSUE TITLE
Render svgs with different attributes in dark and light mode

### ISSUE THREAD

**Issue by ad-chaos** [ratatui/ratatui-website#506]
Its a little hard to read at the moment:

<img width="325" alt="Screenshot 2024-03-11 at 9 31 08 PM" src="https://github.com/ratatui-org/ratatui-website/assets/90276965/0fb63f66-a8d1-41d7-9783-e3851ff10155">

I've [made a PR](https://github.com/agoose77/svgbob-wasm/pull/18) to svgbob-wasm (used by a dependency of remark-svgbob) which adds the ability to specify some settings to svgbob before rendering.

**Comment by kdheepak** [comment]
Thank you for making a PR to svgbob-wasm! I didn't test on dark mode, my bad. If there's any change that I can make to remark-svgbob let me know!

https://github.com/kdheepak/remark-svgbob

**Comment by ad-chaos** [comment]
ah, seems like its fixed!
