### ISSUE TITLE
Ensure code examples in Counter App - Multiple Files are complete

### ISSUE THREAD

**Issue by farmeroy** [ratatui/ratatui-website#52]
I'm currently following along with the book in order to learn Ratatui.

 I think the section on breaking the Counter App into multiple files could be made a bit more beginner friendly by including more explicitly when certain crates are imported, reminding the reader to add the mods to their crate, etc. - it seems like some possibly obvious code has been excluded for brevity.

As an intermediate rustacean, I do enjoy the extra practice filling in some of the gaps, but it occasionally has been a bit frustrating or felt incomplete.

As I'm going through the book at the moment, I am actively taking notes on places where I've had to add to the example code. I would be happy to share those notes or make a pull request including my edits, if either would be helpful.

**Comment by kdheepak** [comment]
>  I would be happy to share those notes or make a pull request including my edits, if either would be helpful.

I'd love to see your notes! If you can make a PR that'll be even better. I did take a stab at cleaning up some of the issues in a linked PR but I'm sure there's more that can be improved.

**Comment by farmeroy** [comment]
I'll start a PR, just adding the bits of code to the examples I had to add to appease the compiler and maybe some small explanations.

**Comment by farmeroy** [comment]
So I rebased from main and then tried to rebase my remote branch from my local branch. Now, there is just a lot more noise from all the diffs between the main and my PR :( Sorry about that -- I haven't done much rebasing before, how can I clean this up for you?

**Comment by kdheepak** [comment]
Do you feel like this issue has been addressed? Can we close it?

**Comment by kdheepak** [comment]
I'll close this issue! Let us know if there's more work that can be done to improve things.
