### ISSUE TITLE
change Twitter logo

### ISSUE THREAD

**Issue by jeevikasirwani** [ratatui/ratatui-website#560]
Changing twitter logo from bird to X

**Comment by joshka** [comment]
Good idea. Would you be inclined to submit a PR for this?

**Comment by jeevikasirwani** [comment]
unable to figure out as the code is in rust

**Comment by joshka** [comment]
> unable to figure out as the code is in rust

No probs - the website code is actually based on https://starlight.astro.build/ if you're interested in contributing in the future.
