### ISSUE TITLE
Add front page content

### ISSUE THREAD

**Issue by joshka** [ratatui/ratatui-website#642]
Right now the front page is just a landing page with links. It looks really pretty, but any real use of the website needs to hit the button that goes deeper into the website. It would be nice to have more information on that page up front.

A couple of inspirations from the starlight showcase:
- https://docs.astronvim.com/ (I like the sidebar icons on this...
- https://dmno.dev/

Some things which would be nice to see on the first page:
- A simple hello world and screenshot
- Some showcase apps
- other ideas for this? @ratatui-org/maintainers ?

**Comment by orhun** [comment]
Random idea: We can have a list of showcase apps and display a random one every time the page is refreshed.

Similar to the background image of <https://coolmodfiles.com/>

**Comment by joshka** [comment]
Just to be clear - I think we should show the sidebar on the first page at https://ratatui.rs

**Comment by joshka** [comment]
https://github.com/ratatui-org/ratatui-website/pull/662 is a stub of this. More can be done to massage the content / layout, but this solves my main gripe that whenever I visit ratatui.rs I usually want some part of the website that's on the sidebar.
