### ISSUE TITLE
Compilation Error in Counter Tutorial

### ISSUE THREAD

**Issue by senchaaa** [ratatui/ratatui-website#649]
Hi there! I was recently working through the [Counter App tutorial](https://ratatui.rs/tutorials/counter-app/) to get started with Ratatui. When I completed the exercise, and went to compile my program, I got an error from the compiler that there was an ambiguous import at the beginning of the [`main.rs` file](https://github.com/ratatui-org/ratatui-website/blob/main/code/counter-app-basic/src/main.rs), between the imports for `prelude` and `widgets::blocks`. These both contain an implementation of the `Position` class, which gets used on line 111. I believe this is because the main ratatui repo [recently added a `Position` type to the `prelude.rs` file.](https://github.com/ratatui-org/ratatui/blob/main/src/prelude.rs), and what we really want to use in this example is the `Position` from the `widgets::blocks` import.

**Comment by joshka** [comment]
Thanks for the heads up - this should be fixed up now. Please let us know if you're still having trouble with this.
I've removed the prelude code in preference for pointing at the actual modules as this was generally easier to understand by many users.
