### ISSUE TITLE
TL;DR The website might need to be re-render as is not in sync with recent changes in this repo

### ISSUE THREAD

**Issue by jubeormk1** [ratatui/ratatui-website#654]
Following the [Basic Counter App][1] I realised that there is a missing ``use ratatui::style::Style`` and accordingly rust check fail with an obvious suggestion:

``` bash
user@LOCAL:~/repos/ratatui-counter-example$ cargo test
   Compiling ratatui-counter-example v0.1.0 (/home/user/repos/ratatui-counter-example)
error[E0433]: failed to resolve: use of undeclared type `Style`
   --> src/main.rs:110:27
    |
110 |         let title_style = Style::new().bold();
    |                           ^^^^^ use of undeclared type `Style`
    |
help: consider importing this struct
    |
94  +     use ratatui::style::Style;
    |
```

It is a minimal error, and I imagine that anyone diving into TUI creation should be able to fix this problem. However it would be good to correct it.

Looking at the example code, I can see the [directive][2], but not in the [Basic Counter App web section][1]. I believe that I have found the Markdown file where the [web tutorial][3] is defined and there everything looks correct as well. I am not familiar with the web pages generation method, I love it though, and might be trigger by the github action [pages build and deployment][4] trigger by @joshka [manually four months ago][5].

Again, checking the [example counter app blame][2], I noticed that the ``use ratatui::style::Style`` was added one week ago, so it might be a mater of re-running the [action][4] again.

I have made a big report of a tiny issue, I hope that you find it useful. In any event, thanks for your work on the tutorials and the templates. Thinking about it, it is possible that other [commits to the main branch][6] have not been updated in the website.

[1] : https://ratatui.rs/tutorials/counter-app/basic-app/#testing-the-ui-output
[2] : https://github.com/ratatui-org/ratatui-website/blame/7ee1e084106fb23b8500b355954c6fd576b43b29/code/counter-app-basic/src/main.rs#L138
[3] : https://github.com/ratatui-org/ratatui-website/blob/main/src/content/docs/tutorials/counter-app/basic-app.md#testing-the-ui-output
[4] : https://github.com/ratatui-org/ratatui-website/actions/workflows/pages/pages-build-deployment
[5] : https://github.com/ratatui-org/ratatui-website/actions/runs/8226178878
[6] : https://github.com/ratatui-org/ratatui-website/commits/main/

**Comment by kdheepak** [comment]
Thanks for reporting! 

The "directive" or the anchor name in this case was `"render test"` but the `use ratatui::style::Style` was outside of that block. I moved it in in a PR and merged it, and the website re-rendered correctly.

The website renders on every commit merged to the `main` branch (except some dependabot commits apparently). So I think that part is working fine.

fwiw @joshka I think we should use `render_test` instead of `render test` for the anchor names. It'll make it more obvious that that is just a name for the block imo. It is easy a glance to misread this as "render the `test` anchor". 

```rust
#[cfg(test)]
mod tests {
{{ #include @code/counter-app-basic/src/main.rs:render test }}
}
```

Or some other alternative like the following?

```rust
{{ #include @code/counter-app-basic/src/main.rs:ANCHOR-render_test }}
```

**Comment by joshka** [comment]
I'd like the import to understand named blocks automatically, like functions, modules, types, so that the anchor comments can be minimized. No real opinion on the anchor names used. Use what works.
