### ISSUE TITLE
Bug in the Counter tutorial on the Ratatui website

### ISSUE THREAD

**Issue by pcgeek86** [ratatui/ratatui-website#733]
I think there's a bug in the **Counter** guide on the Ratatui docs website. 

Under the *Handle Keyboard Events* heading, it doesn't mention that the `#[test]`  should be included in the `tests` module.  It is included in the `impl App`  block. This is a bug because it's a duplicate function name in the `impl` block.

The annotated section should be under `mod tests`, not inside the `impl App` block.

<img width="1343" alt="image" src="https://github.com/user-attachments/assets/8cc4cb36-4d3a-4ea6-b8f1-c7b8a4620023">

**Comment by orhun** [comment]
Good catch! Would you be interested in contributing a fix?

**Comment by christeefy** [comment]
I am interested in contributing a fix, if no one else is taking this up. Should have something in the coming days :)
