### ISSUE TITLE
Question: Road map or schedule of tutorial?

### ISSUE THREAD

**Issue by TieWay59** [ratatui/ratatui-website#9]
It's been a while since the last update, I wonder what's the plan for the tutorial writing? And is it OK to receive an outer contribution for the startup of it?

**Comment by joshka** [comment]
We don't really have a roadmap, and definitely welcome outside contributions. Generally take a read of https://diataxis.fr/ to get an understanding of what we'd like to have. Feel free to contribute in any way you'd like - perhaps that's helping shape the direction of what's needed, or providing information on some concept you've done in an app, or even writing a section of the book.

There's a few people that want to write stuff for this, but they have school / work things happening. Feel free to contribute and come say hi in the discord channel. https://discord.com/channels/1070692720437383208/1080107705672413264

**Comment by TieWay59** [comment]
Thank you, I haven't check the channel before. I'll look into it first.
