### ISSUE TITLE
Constraints array: `as_ref()` or not `as_ref()`?

### ISSUE THREAD

**Issue by j0ni** [ratatui/ratatui-website#94]
I noticed in the json editor tutorial that most places an array of `Constraint` is passed to `Layout::constraints`, it's sent as a ref. But the very last time it's used, setting the `popup_chunks` layout for editing, it is sent without calling `as_ref()`.

While debugging a different thing I fiddled with that and noticed that it made no difference at all, since both seem to be `Into<Vec<Constraint>>` (or at least, no error is raised, and rust-analyzer is happy).

I assume what's happening is the ref is being auto-derefed in most cases - is that correct? If not, what's the mechanism, is `as_ref()` needed/desired, or is it a mistake/leftover from an earlier, (not so) simpler time?

**Comment by kdheepak** [comment]
> I assume what's happening is the ref is being auto-derefed in most cases - is that correct? 

I believe this is the case and we can remove the `.as_ref()` from the tutorial. Let me know if you'd like to make a PR for this! If not, I'll get to it closer to the end of the day.

**Comment by joshka** [comment]
I suspect it's two things:
- copy paste from examples
- LLM generated code

I tend to just use `vec![constraint, constraint]`, but &[constraint, constraint] or even [constraint, constraint] works too in most cases.

**Comment by kdheepak** [comment]
I went ahead and removed the `.as_ref()` in the book as I was making other changes! Thanks for bringing this to our attention.
