### ISSUE TITLE
Suggestion for an edit, json editor exit popup confusion

### ISSUE THREAD

**Issue by j0ni** [ratatui/ratatui-website#95]
The final popup in the json editor tutorial has its own page and contains no context. Since the previous page, the main editor UI, had several chunks of code which are just concatenated to make the content of this block:
```rust
    if let Some(editing) = &app.currently_editing {
```
and didn't end with the closing brace, I just kept going, placing the final popup check inside that block too.

Obviously the conditional
```rust
      if let CurrentScreen::Exiting = app.current_screen {
```
is never true in that context. Because the code is quite long and unfactored, it was not immediately obvious to me what the problem was (until I had an aha, and tried hitting `y`, while exiting, and getting json output as a result).

I think it would be helpful if the last piece of code on the main UI page was followed by an unindented closing brace like so:

```rust
        f.render_widget(value_text, popup_chunks[1]);
    }
```

**Comment by kdheepak** [comment]
Thanks! That is good feedback! Would you like to submit a PR? No worries if you’d like us to fix it instead.

**Comment by j0ni** [comment]
@kdheepak definitely. I was going to do that, probably tomorrow if you all hadn't gotten to it; I wanted to make an issue to link to the PR :)

This material is great btw. The first counter example in particular was excellent, as a walk through the factoring of a simple dozen liner into a well structured extensible app. I'm excited to start the async one next, particularly as it looks like a shoo-in for making the kinds of silly games I want to make.

Thanks for the work.

**Comment by kdheepak** [comment]
Thanks for the kind words! We are glad you are finding it useful. If you have any more suggestions for improving the material, comments and feedback are more than welcome!
